import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ApiProvider } from "@/client/api";
import React from "react";
import Navbar from "@/app/components/nav/navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ApiProvider>
      <html lang="en">
        <Navbar/>
        <body className={inter.className}>
          <main>
            {children}
          </main>
        </body>
      </html>
    </ApiProvider>
  );
}
